import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import 'dotenv/config';
import { db } from '../src/lib/db';
import { runDailyMonitoring,publishOffer } from '../src/lib/monitoring/service';
import { paymentTransaction } from '../src/lib/payment-service';
import { submitTargetedOffer,reviewTargetedOffer,listingRewardSource } from '../src/lib/targeted-offers';
import { targetedOfferValid } from '../src/lib/monitoring/policy';
test('database-backed monitoring history and private targeted offer workflow',{skip:process.env.MONITOR_INTEGRATION_TESTS!=='true'},async t=>{
 assert(['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL!).hostname));process.env.PAYMENT_PROVIDER='demo';const tag=randomUUID();const category=await db.category.findFirstOrThrow();const users=await Promise.all(['admin','owner','outsider'].map((r)=>db.user.create({data:{email:`monitor-${tag}-${r}@example.com`,passwordHash:'not-a-login-hash',role:r==='admin'?'ADMIN':'USER',isDemo:true}})));const [admin,owner,outsider]=users;
 const p=await db.program.create({data:{name:'Monitor fixture',slug:`monitor-${tag}`,description:'Demo fixture',officialDomain:'example.com',categoryId:category.id,referrerRewardCents:10000,restrictionStatus:'ALLOWED',publicSharingAllowed:true,cashBountyAllowed:true,thirdPartyMarketplaceAllowed:true,isDemo:true}});
 const original=await db.programOffer.create({data:{programId:p.id,scopeKey:'PUBLIC',isCurrent:true,reviewStatus:'VERIFIED',referrerRewardType:'CASH',referrerRewardAmount:10000,estimatedReferrerValueCents:10000,verifiedAt:new Date(),isDemo:true}});await db.program.update({where:{id:p.id},data:{currentPublicOfferId:original.id}});
 await db.programSource.create({data:{programId:p.id,url:'demo://fixture?scenario=increase&reward=12000',sourceType:'OFFICIAL_REFERRAL_PAGE',adapter:'demo'}});
 await t.test('monitor preserves public offer, records candidate and queue, never claims real retrieval',async()=>{const r=await runDailyMonitoring({manual:true,programId:p.id});assert('id' in r);const after=await db.program.findUniqueOrThrow({where:{id:p.id}});assert.equal(after.currentPublicOfferId,original.id);assert.equal(after.lastSuccessfulCheckAt,null);assert(after.lastChangedAt);assert.equal(await db.programOffer.count({where:{programId:p.id}}),2);assert(await db.monitoringReview.count({where:{programId:p.id,status:'PENDING'}}));});
 await t.test('repeated observations deduplicate candidates and reviews',async()=>{await runDailyMonitoring({manual:true,programId:p.id});assert.equal(await db.programOffer.count({where:{programId:p.id}}),2);});
 await t.test('review publishes new version and retains old facts',async()=>{const candidate=await db.programOffer.findFirstOrThrow({where:{programId:p.id,isCurrent:false}});await paymentTransaction(tx=>publishOffer(tx,candidate,'ADMIN_TEST_REVIEW',admin.id));const prior=await db.programOffer.findUniqueOrThrow({where:{id:original.id}});assert.equal(prior.referrerRewardAmount,10000);assert.equal(prior.isCurrent,false);assert(prior.validUntil);});
 await t.test('geographic variant never replaces nationwide current offer',async()=>{await db.programSource.updateMany({where:{programId:p.id},data:{url:'demo://fixture?scenario=location'}});await runDailyMonitoring({manual:true,programId:p.id});const scoped=await db.programOffer.findFirstOrThrow({where:{programId:p.id,scopeKey:'LOCATION:US:PA:Philadelphia'}});const before=(await db.program.findUniqueOrThrow({where:{id:p.id}})).currentPublicOfferId;await paymentTransaction(tx=>publishOffer(tx,scoped,'ADMIN_LOCATION_TEST',admin.id));assert.equal((await db.program.findUniqueOrThrow({where:{id:p.id}})).currentPublicOfferId,before);});
 await t.test('terms hash changes append snapshots and queue manual review',async()=>{const source=await db.programSource.create({data:{programId:p.id,url:'demo://terms?scenario=stable',sourceType:'OFFICIAL_TERMS',adapter:'demo'}});await runDailyMonitoring({manual:true,programId:p.id});await db.programSource.update({where:{id:source.id},data:{url:'demo://terms?scenario=terms'}});await runDailyMonitoring({manual:true,programId:p.id});await db.programSource.update({where:{id:source.id},data:{url:'demo://terms?scenario=terms&revision=2'}});await runDailyMonitoring({manual:true,programId:p.id});assert((await db.programTermsSnapshot.count({where:{programId:p.id}}))>=3);});
 await t.test('failure records unavailable and preserves public facts',async()=>{await db.programSource.updateMany({where:{programId:p.id},data:{active:false}});await db.programSource.create({data:{programId:p.id,url:'demo://failure?scenario=failure',sourceType:'OFFICIAL_REFERRAL_PAGE',adapter:'demo'}});const before=(await db.program.findUniqueOrThrow({where:{id:p.id}})).currentPublicOfferId;await runDailyMonitoring({manual:true,programId:p.id});const after=await db.program.findUniqueOrThrow({where:{id:p.id}});assert.equal(after.currentPublicOfferId,before);assert.equal(after.consecutiveFailures,1);assert(await db.monitoringReview.count({where:{programId:p.id,type:'SOURCE_FAILURE'}}));});
 const targeted=await paymentTransaction(tx=>submitTargetedOffer(tx,owner.id,{programId:p.id,referrerRewardType:'CASH',referrerRewardAmount:20000,qualificationRequirement:'Account specific qualifying steps',evidence:{data:Buffer.from('%PDF-fixture'),mimeType:'application/pdf',sizeBytes:12,fileName:'private.pdf'}}));
 await t.test('private targeted submission does not change public reward',async()=>{const after=await db.program.findUniqueOrThrow({where:{id:p.id}});assert.equal(after.referrerRewardCents,12000);assert.equal(targeted.verificationStatus,'PENDING_REVIEW');await assert.rejects(()=>paymentTransaction(tx=>listingRewardSource(tx,owner.id,p.id,targeted.id)),/unverified/);});
 await t.test('admin reviews targeted proof and only owner can use it',async()=>{await assert.rejects(()=>reviewTargetedOffer(outsider.id,targeted.id,'approve','Evidence reviewed carefully'),/Administrator/);const verified=await reviewTargetedOffer(admin.id,targeted.id,'approve','Private evidence reviewed carefully');assert(targetedOfferValid(verified));const source=await paymentTransaction(tx=>listingRewardSource(tx,owner.id,p.id,targeted.id));assert.equal(source.valueCents,20000);await assert.rejects(()=>paymentTransaction(tx=>listingRewardSource(tx,outsider.id,p.id,targeted.id)),/another account/);});
 await t.test('expiration disables use immediately even before scheduled sweep',async()=>{await db.targetedReferralOffer.update({where:{id:targeted.id},data:{verificationExpiresAt:new Date(0)}});await assert.rejects(()=>paymentTransaction(tx=>listingRewardSource(tx,owner.id,p.id,targeted.id)),/expired/);});
 await t.test('active monitoring lease prevents duplicate worker runs',async()=>{const marker=await db.monitoringRun.create({data:{runKey:`lease-${tag}`,leaseUntil:new Date(Date.now()+60000)}});const result=await runDailyMonitoring({manual:true,programId:p.id});assert('duplicate' in result);await db.monitoringRun.update({where:{id:marker.id},data:{status:'COMPLETED'}});});
 await t.test('new extraction metadata and permission facts remain append-only',async()=>{
  const run=await db.monitoringRun.findFirstOrThrow({where:{snapshots:{some:{source:{programId:p.id}}}}});const source=await db.programSource.findFirstOrThrow({where:{programId:p.id}});
  const snapshot=await db.programSourceSnapshot.create({data:{sourceId:source.id,runId:run.id,confidenceScore:.97,extractionMethod:'FIXTURE',rawSnapshotHash:'fixture-hash',extractionStatus:'AI_EXTRACTED',structuredData:{publicPostingAllowed:'no'}}});
  await assert.rejects(()=>db.programSourceSnapshot.update({where:{id:snapshot.id},data:{confidenceScore:1}}));
  await assert.rejects(()=>db.programSourceSnapshot.create({data:{sourceId:source.id,runId:run.id,confidenceScore:1.5}}));
  await assert.rejects(()=>db.programOffer.update({where:{id:original.id},data:{publicPostingAllowed:'yes'}}));
 });
 await t.test('inactive programs are not checked by the scheduled/manual due batch',async()=>{
  await db.program.update({where:{id:p.id},data:{catalogActive:false}});const result=await runDailyMonitoring({manual:true,programId:p.id});assert('programsQueued' in result);assert.equal(result.programsQueued,0);await db.program.update({where:{id:p.id},data:{catalogActive:true}});
 });
 await t.test('reviewed points rewards clear stale cash caps and pause oversized public listings',async()=>{
  const listing=await db.referralListing.create({data:{programId:p.id,referrerId:owner.id,referralUrl:'https://example.com/ref',approvedReferralUrl:'https://example.com/ref',referrerRewardCents:12000,bountyCents:6000,status:'ACTIVE',isDemo:true}});
  const points=await db.programOffer.create({data:{programId:p.id,referrerRewardType:'POINTS',referrerRewardAmount:90000,referrerRewardCurrency:'POINTS',estimatedReferrerValueCents:null,isDemo:true}});
  await paymentTransaction(tx=>publishOffer(tx,points,'ADMIN_POINTS_REVIEW_TEST',admin.id));
  assert.equal((await db.program.findUniqueOrThrow({where:{id:p.id}})).referrerRewardCents,0);
  assert.equal((await db.referralListing.findUniqueOrThrow({where:{id:listing.id}})).status,'DISABLED');
  assert.equal((await db.programOffer.findUniqueOrThrow({where:{id:original.id}})).referrerRewardAmount,10000);
 });
 await db.$disconnect();
});
