import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle2, FileText, ShieldCheck } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { confirmCompletionAction, openDisputeAction, reportCompletionAction, sendMessageAction, submitReviewAction } from "@/lib/actions";
import { ActionForm, SubmitButton } from "@/components/action-form";
import { Field, Money, PageHeading, ProgramMark, StatusBadge } from "@/components/ui";

export default async function TransactionPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const transaction = await db.referralTransaction.findFirst({
    where: { id, ...(user.role === "ADMIN" ? {} : { OR: [{ referrerId: user.id }, { referredUserId: user.id }] }) },
    include: { program: true, listing: true, referrer: { include: { profile: true } }, referredUser: { include: { profile: true } }, statusHistory: { orderBy: { createdAt: "asc" } }, messages: { include: { sender: { include: { profile: true } } }, orderBy: { createdAt: "asc" }, take: 200 }, evidence: { select: { id:true,fileName:true,mimeType:true,sizeBytes:true,createdAt:true } }, disputes: true, reviews: true },
  });
  if (!transaction) notFound();
  const isReferrer = transaction.referrerId === user.id;
  const isCustomer = transaction.referredUserId === user.id;
  const participant = isReferrer || isCustomer;
  const reportable = ["PENDING","LINK_OPENED"].includes(transaction.status);
  const confirmable = ["SIGNUP_REPORTED","AWAITING_VERIFICATION"].includes(transaction.status);
  const dispute = transaction.disputes[0];
  const canDispute = participant && !dispute && !["PAID","CANCELLED","REJECTED"].includes(transaction.status);
  const canReview = participant && transaction.status === "PAID" && !transaction.reviews.some(r=>r.reviewerId === user.id);
  return <div className="stack"><Link href="/dashboard/transactions" className="text-link"><ArrowLeft size={15}/>Back to transactions</Link><PageHeading eyebrow="REFERRAL DETAILS" title={transaction.program.name} description={`Transaction ${transaction.id.slice(-8).toUpperCase()} · Started ${transaction.createdAt.toLocaleDateString("en-US")}`} actions={<StatusBadge status={transaction.status}/>}/>
    {transaction.isDemo && <div className="notice notice-warning"><span className="badge badge-demo">Demo transaction</span>This referral and its balance are for demonstration. No real funds are transferred.</div>}
    <div className="grid-two"><section className="panel"><div className="panel-header"><h2>Your offer</h2><ProgramMark name={transaction.program.name} slug={transaction.program.slug} size="sm"/></div><dl className="detail-list"><div><dt>Cash bounty offered</dt><dd><Money cents={transaction.bountyCents}/></dd></div><div><dt>Marketplace success fee</dt><dd><Money cents={transaction.feeCents}/></dd></div><div><dt>Customer receives</dt><dd><strong><Money cents={transaction.netPayoutCents}/></strong></dd></div><div><dt>Reserved bounty</dt><dd><Money cents={transaction.reservedCents}/></dd></div><div><dt>Referrer</dt><dd><Link href={`/profile/${transaction.referrer.profile?.username}`}>@{transaction.referrer.profile?.username || "member"}</Link></dd></div><div><dt>Customer</dt><dd>@{transaction.referredUser.profile?.username || "member"}</dd></div><div><dt>Referrer confirmation</dt><dd>{transaction.referrerConfirmedAt ? "Confirmed" : "Awaiting confirmation"}</dd></div></dl><div className="panel-body"><strong>Requirements</strong><p className="muted">{transaction.listing.requirements || transaction.program.eligibilityNotes}</p>{isCustomer && ["PENDING","LINK_OPENED"].includes(transaction.status) && <Link href={`/go/${transaction.id}`} className="button button-secondary" target="_blank" rel="noopener noreferrer">Open tracked referral link ↗</Link>}</div></section>
    <section className="panel"><div className="panel-header"><h2>Status history</h2><ShieldCheck size={18}/></div><ol className="timeline">{transaction.statusHistory.map(h=><li key={h.id}><span className="timeline-dot"/><div><StatusBadge status={h.toStatus}/><p className="tiny muted">{h.createdAt.toLocaleString("en-US")}</p>{h.note && <p>{h.note}</p>}</div></li>)}</ol></section></div>
    {isCustomer && reportable && <section className="panel"><div className="panel-header"><h2>Completed the requirements?</h2><CheckCircle2 size={18}/></div><ActionForm action={reportCompletionAction} className="panel-body stack"><input type="hidden" name="transactionId" value={id}/><Field label="Completion note"><textarea name="note" rows={3} required minLength={10} maxLength={3000} placeholder="Tell the referrer what you completed and when."/></Field><Field label="Proof (optional)" hint="Upload a JPG, PNG, or PDF up to 5 MB. Hide any account numbers or sensitive details."><input name="evidence" type="file" accept="image/jpeg,image/png,application/pdf"/></Field><div><SubmitButton pendingLabel="Submitting completion…">I completed this referral</SubmitButton></div></ActionForm></section>}
    {isReferrer && confirmable && !transaction.referrerConfirmedAt && <section className="panel"><div className="panel-header"><h2>Confirm referral completion</h2></div><div className="panel-body stack"><p className="muted">The customer has reported completion. Confirm that the program requirements were met. An administrator performs the final verification.</p><ActionForm action={confirmCompletionAction}><input type="hidden" name="transactionId" value={id}/><SubmitButton>Confirm completion</SubmitButton></ActionForm></div></section>}
    {(transaction.completionNote || transaction.evidence.length > 0) && <section className="panel"><div className="panel-header"><h2>Completion & evidence</h2></div><div className="panel-body stack">{transaction.completionNote && <p>{transaction.completionNote}</p>}{transaction.evidence.map(e=><Link className="evidence-file" href={`/api/evidence/${e.id}`} target="_blank" rel="noopener noreferrer" key={e.id}><FileText size={18}/><span>{e.fileName}</span><span className="tiny muted">{Math.ceil(e.sizeBytes/1024)} KB</span><span>View ↗</span></Link>)}</div></section>}
    <section className="panel"><div className="panel-header"><h2>Conversation</h2><span className="tiny muted">Private to participants and authorized admins</span></div><div className="panel-body stack"><div className="message-list">{transaction.messages.length ? transaction.messages.map(m=><div className={`message-bubble ${m.senderId === user.id ? "mine" : ""}`} key={m.id}><div className="message-meta"><strong>@{m.sender.profile?.username || "member"}</strong><time>{m.createdAt.toLocaleString("en-US")}</time></div><p>{m.body}</p></div>) : <p className="muted">No messages yet. Keep questions and updates together here.</p>}</div>{participant && <ActionForm action={sendMessageAction} className="stack"><input type="hidden" name="transactionId" value={id}/><Field label="Message"><textarea name="body" rows={3} required minLength={1} maxLength={3000} placeholder="Write a message…"/></Field><div><SubmitButton>Send message</SubmitButton></div></ActionForm>}</div></section>
    {dispute && <section className="panel"><div className="panel-header"><h2>Dispute</h2><StatusBadge status={dispute.status}/></div><div className="panel-body stack"><strong>{dispute.reason.replaceAll("_"," ")}</strong><p>{dispute.details}</p>{dispute.resolution && <div className="notice notice-success">Resolution: {dispute.resolution}</div>}{user.role === "ADMIN" && <Link href="/admin?tab=disputes" className="button button-secondary">Review in admin console</Link>}</div></section>}
    {canDispute && <details className="panel disclosure"><summary>Open a dispute</summary><ActionForm action={openDisputeAction} className="panel-body stack"><input type="hidden" name="transactionId" value={id}/><Field label="Reason"><select name="reason" required defaultValue=""><option value="" disabled>Select a reason</option>{["REFERRAL_NOT_TRACKED","BOUNTY_NOT_PAID","UNCLEAR_REQUIREMENTS","NOT_QUALIFIED","OFFER_CHANGED","DUPLICATE_REFERRAL","SUSPECTED_FRAUD","OTHER"].map(r=><option key={r} value={r}>{r.replaceAll("_"," ").toLowerCase()}</option>)}</select></Field><Field label="What happened?"><textarea name="description" rows={3} required minLength={10} maxLength={3000}/></Field><div><SubmitButton className="button button-secondary">Submit dispute</SubmitButton></div></ActionForm></details>}
    {canReview && <section className="panel"><div className="panel-header"><h2>How did it go?</h2><span className="badge badge-success">Verified completed transaction</span></div><ActionForm action={submitReviewAction} className="panel-body stack"><input type="hidden" name="transactionId" value={id}/><Field label="Rating"><select name="rating" defaultValue="5" required>{[5,4,3,2,1].map(n=><option value={n} key={n}>{"★".repeat(n)} · {n} star{n !== 1 ? "s" : ""}</option>)}</select></Field><Field label="Review (optional)"><textarea name="body" rows={3} maxLength={2000} placeholder="Share your experience with this participant."/></Field><div><SubmitButton>Publish review</SubmitButton></div></ActionForm></section>}
    {transaction.reviews.length > 0 && <section className="panel"><div className="panel-header"><h2>Transaction reviews</h2></div><div className="panel-body stack">{transaction.reviews.map(r=><div key={r.id}><strong>{"★".repeat(r.rating)} · {r.reviewerRole.toLowerCase()}</strong>{r.body && <p>{r.body}</p>}{r.isDemo && <span className="badge badge-demo">Demo review</span>}</div>)}</div></section>}
  </div>;
}
