import Link from "next/link";
import type { Metadata } from "next";
import { ArrowUpRight, BadgeCheck, Banknote, Check, Globe2, HeartHandshake, Plane, Search, ShieldCheck, ShoppingBag, Sparkles, Wallet } from "lucide-react";
import { db } from "@/lib/db";
import { calculateFees, canUseProgram, DEFAULT_FEE_CONFIG } from "@/lib/marketplace";
import { ProgramSearch } from "@/components/search";
import { Money, ProgramMark } from "@/components/ui";
import { ProgramCard } from "@/components/program-card";
import { publicReferrerSelect, referrerStats } from "@/components/offer-card";

export const metadata: Metadata = { alternates: { canonical: "/" } };
const faqs = [
  { question: "How is this different from a referral-code site?", answer: "Referrers compete by sharing part of their reward with you. Compare the bounty, success fee, payout record, and requirements before choosing an offer." },
  { question: "When do I receive my bounty?", answer: "Complete the program’s requirements, report completion in your dashboard, and submit any requested proof. An admin verifies the referral before the bounty can be paid. The current demo uses simulated balances and payouts, with no real money transferred." },
  { question: "Is there a fee to join or list a referral?", answer: "There are no subscriptions or monthly listing fees. A clearly disclosed success fee is deducted from the offered bounty after a successful referral. You see your net bounty before starting." },
  { question: "Can any company’s referral program be listed?", answer: "Only programs approved for public referral sharing, cash incentives, and third-party marketplace use can accept offers. Unknown, restricted, and prohibited programs are disabled pending review. Demo information is illustrative and is not a verified current company promotion." },
];

export default async function HomePage() {
  const [programs, categories, fee] = await Promise.all([
    db.program.findMany({ include: { category: true, listings: { where: { status: "ACTIVE", availableSlots: { gt: 0 }, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, select: { bountyCents: true, isFunded: true }, take: 100 } }, orderBy: [{ restrictionStatus: "asc" }, { name: "asc" }], take: 100 }),
    db.category.findMany({ orderBy: { name: "asc" }, take: 8 }),
    db.feeSetting.findUnique({ where: { id: "global" } }),
  ]);
  const demoProgram = await db.program.findFirst({ where: { slug: "orbit-money" }, include: { category: true, listings: { where: { status: "ACTIVE", availableSlots: { gt: 0 } }, include: { referrer: { select: publicReferrerSelect } }, orderBy: { bountyCents: "desc" }, take: 3 } } });
  const availablePrograms = programs.filter(canUseProgram);
  const featured = [...availablePrograms.sort((a, b) => Math.max(0, ...b.listings.map(l => l.bountyCents)) - Math.max(0, ...a.listings.map(l => l.bountyCents))).slice(0, 4), ...programs.filter(p => !canUseProgram(p)).slice(0, 4)];
  const icons = [Banknote, ShoppingBag, Plane, Globe2, Wallet];
  const structured = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.question, acceptedAnswer: { "@type": "Answer", text: f.answer } })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured).replaceAll("<", "\\u003c") }} />
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" />The referral marketplace</div><h1>Never use a<br />referral link<br /><em>for free.</em></h1><p>Find people willing to share their referral reward with you.</p><ProgramSearch programs={programs.map(p => ({ name: p.name, slug: p.slug, category: p.category.name }))} /><div className="popular-searches"><span>Explore:</span>{["SoFi", "Rakuten", "Uber", "Dropbox"].map(name => <Link key={name} href={`/referral/${name.toLowerCase()}`}>{name}</Link>)}</div><div className="hero-demo"><span className="badge badge-demo">Demo marketplace</span><span>Sample offers. Simulated payments. Real product flows.</span></div></div><div className="hero-art"><div className="hero-art-label"><strong><span className="live-dot" />People sharing their rewards</strong><span className="badge badge-demo">Demo</span></div><div className="illustration-program"><ProgramMark name={demoProgram?.name || "Orbit Money"} slug={demoProgram?.slug} /><div><h3>{demoProgram?.name || "Orbit Money"}</h3><p>One program. Competing offers.</p></div></div>{demoProgram?.listings.map((offer, index) => {
      const net = calculateFees(offer.bountyCents, fee || DEFAULT_FEE_CONFIG).netPayoutCents;
      const stats = referrerStats(offer.referrer);
      return <Link href={`/referral/${demoProgram.slug}`} className={`hero-offer ${index === 0 ? "hero-offer-best" : ""}`} key={offer.id}>{index === 0 && <span className="badge">Highest demo bounty</span>}<span className={`avatar ${index === 1 ? "avatar-lilac" : index === 2 ? "avatar-peach" : ""}`}>{offer.referrer.profile?.displayName.split(" ").map(n => n[0]).slice(0, 2).join("")}</span><div className="hero-offer-name"><strong>{offer.referrer.profile?.displayName}</strong><small><BadgeCheck size={11} />{stats.completedReferrals} demo referrals completed</small></div><div className="hero-offer-value"><strong><Money cents={net} /></strong><small>extra for you, after fees</small></div></Link>;
    })}<div className="hero-art-foot"><span>Compare. Choose. Share the reward.</span><Link href={`/referral/${demoProgram?.slug || "orbit-money"}`}>View offers<ArrowUpRight size={13} /></Link></div><div className="hero-floating-note"><HeartHandshake size={17} />Their referral. Your extra reward.</div></div></div></section>
    <div className="trust-strip"><div className="container trust-inner"><div className="trust-item"><ShieldCheck size={18} />Reputation you can compare</div><div className="trust-item"><Wallet size={18} />Transparent fees, before you start</div><div className="trust-item"><Check size={18} />No subscriptions. No monthly fees.</div></div></div>
    <section className="section"><div className="container"><div className="section-header"><div><p className="eyebrow">Find your next reward</p><h2>Good referrals pay you back.</h2><p>Explore programs. Compare offers. Keep more of the reward.</p></div><Link href="/marketplace" className="text-link">Explore all offers<ArrowUpRight size={16} /></Link></div><div className="category-tabs"><Link href="/marketplace" className="category-tab active"><Sparkles size={14} />All programs</Link>{categories.slice(0, 5).map((category, i) => { const Icon = icons[i]; return <Link href={`/category/${category.slug}`} key={category.id} className="category-tab"><Icon size={14} />{category.name}</Link>; })}</div><div className="program-grid">{featured.map(program => <ProgramCard key={program.id} program={program} />)}</div><p className="section-caption"><span className="badge badge-demo">Demo data</span>All sample rewards are illustrative. Known company programs require terms review before bounty offers can be activated.</p></div></section>
    <section id="how-it-works" className="section how-section"><div className="container"><div className="how-header"><p className="eyebrow">A better deal for everyone</p><h2 style={{ marginTop: 12 }}>Someone gets a referral.<br />You get rewarded.</h2></div><div className="how-grid"><div className="how-step"><span className="step-number">01</span><div className="step-icon"><Search size={29} strokeWidth={1.5} /></div><h3>Find your program.</h3><p>Search for a company you’re ready to try. Compare bounties, requirements, and each referrer’s track record.</p></div><div className="how-step"><span className="step-number">02</span><div className="step-icon"><ArrowUpRight size={30} strokeWidth={1.5} /></div><h3>Choose your offer.</h3><p>Start a tracked referral, use the approved link, and complete the program’s signup requirements.</p></div><div className="how-step"><span className="step-number">03</span><div className="step-icon"><Wallet size={29} strokeWidth={1.5} /></div><h3>Share the reward.</h3><p>Report completion in your dashboard. After verification, the promised bounty is released, minus the disclosed fee.</p></div></div></div></section>
    <section className="referrer-section"><div className="container"><div className="referrer-box"><div><p className="eyebrow">For the one with the referral</p><h2>Have referral bonuses<br />collecting dust?</h2><p>List your referral. Set your offer. Pay only when you get a successful referral.</p><Link href="/dashboard/listings/new" className="button button-primary">List a referral<ArrowUpRight size={17} /></Link></div><div className="referrer-illustration" aria-label="Example bounty breakdown"><div className="referrer-circle"><div className="referrer-card"><h4>Everyone gets a little more.</h4><div className="mini-line"><span>Example referral reward</span><span>$100</span></div><div className="mini-line"><span>Bounty you offer</span><span>$50</span></div><div className="mini-line"><span>Example success fee</span><span>$5</span></div><div className="mini-total"><span>Your customer gets</span><span>$45</span></div><p style={{ fontSize: 9, marginTop: 12, color: "#748366" }}>Illustration using a 10% success fee.</p></div><div className="referrer-icon"><ArrowUpRight size={24} /></div></div></div></div></div></section>
    <section className="section" style={{ paddingTop: 20 }}><div className="container faq-grid"><div className="faq-intro"><p className="eyebrow">A few things to know</p><h2>Good questions.<br />Clear answers.</h2></div><div className="faq-list">{faqs.map(faq => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></div></section>
  </>;
}
