import Link from "next/link";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import type { Category, Program } from "@prisma/client";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { isDemoMode } from "@/lib/config";
import { adminCategoryAction, adminFeeAction, adminFraudAction, adminListingAction, adminPayAction, adminProgramAction, adminResolveDisputeAction, adminUserAction, adminVerifyAction } from "@/lib/actions";
import { ActionForm, SubmitButton } from "@/components/action-form";
import { EmptyState, Field, Money, PageHeading, StatusBadge } from "@/components/ui";

const tabs = ["analytics","users","programs","categories","listings","transactions","verification","disputes","payments","fees","fraud","restrictions","terms","audit"];
const label = (s:string) => s === "fraud" ? "Fraud flags" : s === "verification" ? "Verification queue" : s === "audit" ? "Audit log" : s.charAt(0).toUpperCase()+s.slice(1);

function ProgramEditor({ program, categories }: { program?: Program; categories: Category[] }) {
  return <ActionForm action={adminProgramAction} className="stack">
    {program && <input name="programId" type="hidden" value={program.id}/>}
    <div className="form-grid"><Field label="Program name"><input name="name" defaultValue={program?.name || ""} required maxLength={100}/></Field><Field label="URL slug"><input name="slug" defaultValue={program?.slug || ""} required pattern="[a-z0-9-]+" maxLength={100}/></Field></div>
    <div className="form-grid"><Field label="Category"><select name="categoryId" defaultValue={program?.categoryId || ""} required><option value="" disabled>Choose a category</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Official domain" hint="Approved referral links must match this domain or its subdomains."><input name="officialDomain" defaultValue={program?.officialDomain || ""} placeholder="company.com" required/></Field></div>
    <Field label="Description"><textarea name="description" defaultValue={program?.description || ""} rows={3} required maxLength={4000}/></Field>
    <div className="form-grid"><Field label="Official signup benefit"><input name="officialBenefit" defaultValue={program?.officialBenefit || ""} maxLength={500}/></Field><Field label={program && program.rewardType !== "CASH" ? "Estimated referrer reward (USD)" : "Normal referrer reward (USD)"}><input name="normalReward" type="number" min="0" step="0.01" defaultValue={(program?.referrerRewardCents || 0)/100}/></Field></div>
    <div className="form-grid"><Field label="Eligible countries"><input name="countries" defaultValue={program?.countries.join(", ") || "US"} placeholder="US, CA"/></Field><Field label="Terms URL"><input name="termsUrl" type="url" defaultValue={program?.termsUrl || ""} placeholder="https://company.com/referral-terms"/></Field></div>
    <Field label="Eligibility notes"><textarea name="eligibilityNotes" defaultValue={program?.eligibilityNotes || ""} rows={2} maxLength={3000}/></Field>
    <Field label="Restriction status" hint="Marketplace activity requires ALLOWED plus public sharing, cash bounty, and third-party marketplace permission."><select name="restrictionStatus" defaultValue={program?.restrictionStatus || "UNKNOWN"}>{["UNKNOWN","ALLOWED","RESTRICTED","PROHIBITED"].map(s=><option value={s} key={s}>{s}</option>)}</select></Field>
    <fieldset className="permission-checkboxes"><legend>Verified program permissions</legend>{[{name:"publicSharingAllowed",text:"Public sharing allowed"},{name:"cashBountyAllowed",text:"Cash bounty sharing allowed"},{name:"thirdPartyMarketplaceAllowed",text:"Third-party marketplace allowed"},{name:"paidPromotionAllowed",text:"Paid promotion allowed"}].map(p=><label key={p.name}><input name={p.name} type="checkbox" defaultChecked={Boolean(program?.[p.name as "publicSharingAllowed" | "cashBountyAllowed" | "thirdPartyMarketplaceAllowed" | "paidPromotionAllowed"])}/>{p.text}</label>)}</fieldset>
    <Field label="Admin notes" hint="Record the source and reason for the permission decision. Saving creates a terms history and audit record."><textarea name="adminNotes" defaultValue={program?.adminNotes || ""} rows={3} maxLength={3000}/></Field>
    <div><SubmitButton>{program ? "Save program & terms" : "Create program"}</SubmitButton></div>
  </ActionForm>;
}

async function Analytics() {
  const monthAgo = new Date();
  monthAgo.setDate(monthAgo.getDate() - 30);
  const [all, paid, activeListings, activeUsers, newUsers, disputed, clicks] = await Promise.all([
    db.referralTransaction.aggregate({_sum:{bountyCents:true},_avg:{bountyCents:true},_count:true}),
    db.referralTransaction.aggregate({where:{status:"PAID"},_sum:{bountyCents:true,feeCents:true,netPayoutCents:true},_count:true}),
    db.referralListing.count({where:{status:"ACTIVE"}}), db.user.count({where:{isSuspended:false}}),
    db.user.count({where:{createdAt:{gte:monthAgo}}}),db.dispute.count(),db.referralClick.count(),
  ]);
  const metrics = [
    {name:"Completed gross transaction value",value:<Money cents={paid._sum.bountyCents || 0}/>},
    {name:"Total bounty value (all statuses)",value:<Money cents={all._sum.bountyCents || 0}/>},
    {name:"Marketplace fees earned",value:<Money cents={paid._sum.feeCents || 0}/>},
    {name:"Net customer bounties paid",value:<Money cents={paid._sum.netPayoutCents || 0}/>},
    {name:"Completed referrals",value:paid._count}, {name:"Active listings",value:activeListings},
    {name:"Active users",value:activeUsers}, {name:"New users · last 30 days",value:newUsers},
    {name:"Average bounty",value:<Money cents={Math.round(all._avg.bountyCents || 0)}/>},
    {name:"Conversion rate",value:`${all._count ? Math.round(paid._count/all._count*100) : 0}%`},
    {name:"Dispute rate",value:`${all._count ? Math.round(disputed/all._count*100) : 0}%`},
    {name:"Transaction volume",value:all._count}, {name:"Tracked clicks",value:clicks},
  ];
  return <div className="stack"><div className="metrics-grid">{metrics.map(m=><div className="metric-card" key={m.name}><span className="metric-label">{m.name}</span><strong className="metric-value">{m.value}</strong></div>)}</div><div className="notice">Metrics use database records. Conversion is paid referrals divided by all referrals; dispute rate is disputes divided by all referrals. Financial totals include only successful payments where indicated.</div></div>;
}

async function Users() {
  const users = await db.user.findMany({include:{profile:true,wallet:true,_count:{select:{listings:true,referralsOffered:true,referralsUsed:true}}},orderBy:{createdAt:"desc"},take:100});
  return <section className="panel table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Activity</th><th>Available wallet</th><th>Joined</th><th>Access</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.profile?.displayName || "Member"}</strong><span className="tiny muted">@{u.profile?.username} · {u.email}</span>{u.isDemo && <span className="badge badge-demo">Demo user</span>}</td><td>{u.role}</td><td className="tiny">{u._count.listings} listings<br/>{u._count.referralsOffered+u._count.referralsUsed} referrals</td><td><Money cents={u.wallet?.availableCents || 0}/></td><td className="tiny">{u.createdAt.toLocaleDateString("en-US")}</td><td><ActionForm action={adminUserAction} className="inline-form"><input type="hidden" name="userId" value={u.id}/><select name="status" defaultValue={u.isSuspended ? "SUSPENDED" : "ACTIVE"} aria-label={`Account status for ${u.profile?.username}`}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select><SubmitButton className="button button-secondary button-sm">Save access</SubmitButton></ActionForm></td></tr>)}</tbody></table></section>;
}

async function Programs({ mode }: { mode: string }) {
  const [programs,categories] = await Promise.all([db.program.findMany({include:{category:true,termsHistory:{orderBy:{checkedAt:"desc"},take:5}},orderBy:{name:"asc"},take:100}),db.category.findMany({orderBy:{name:"asc"}})]);
  return <div className="stack">{mode === "programs" && <details className="panel disclosure"><summary>Create a program</summary><div className="panel-body"><ProgramEditor categories={categories}/></div></details>}
    {programs.map(p=><details className="panel disclosure" key={p.id}><summary><span>{p.name} <span className="tiny muted">{p.category.name}</span></span><span className="inline-badges">{p.isDemo && <span className="badge badge-demo">Demo</span>}<StatusBadge status={p.restrictionStatus}/></span></summary><div className="panel-body stack"><div className="notice notice-warning"><AlertTriangle size={17}/><span>{p.isDemo ? "Demo program values and permissions are fictional examples. " : ""}Permission must be backed by the program’s published terms. UNKNOWN, RESTRICTED, or PROHIBITED disables new marketplace activity.</span></div><p className="tiny muted">Last terms check: {p.termsLastChecked?.toLocaleDateString("en-US") || "Not checked"} · Last reward verification: {p.lastVerifiedAt?.toLocaleDateString("en-US") || "Not verified"}</p><ProgramEditor program={p} categories={categories}/>{mode === "terms" && <div><h3>Terms history</h3>{p.termsHistory.length ? p.termsHistory.map(h=><div className="audit-entry" key={h.id}><time className="tiny muted">{h.checkedAt.toLocaleString("en-US")}</time><p>{h.summary}</p>{h.termsUrl && <a className="text-link" href={h.termsUrl} target="_blank" rel="noopener noreferrer">Recorded terms ↗</a>}</div>) : <p className="muted">No terms history recorded.</p>}</div>}</div></details>)}
    {!programs.length && <EmptyState title="No programs yet" description="Create a program and review its terms before approving offers."/>}
  </div>;
}

async function Categories() {
  const categories = await db.category.findMany({include:{_count:{select:{programs:true}}},orderBy:{name:"asc"}});
  return <div className="stack"><section className="panel"><div className="panel-header"><h2>Create category</h2></div><ActionForm action={adminCategoryAction} className="panel-body stack"><div className="form-grid"><Field label="Category name"><input name="name" required maxLength={100}/></Field><Field label="Category slug"><input name="slug" required pattern="[a-z0-9-]+" maxLength={100}/></Field></div><Field label="Description"><input name="description" maxLength={500}/></Field><div><SubmitButton>Create category</SubmitButton></div></ActionForm></section>{categories.map(c=><details className="panel disclosure" key={c.id}><summary>{c.name}<span className="tiny muted">{c._count.programs} programs{c.isDemo ? " · Demo" : ""}</span></summary><ActionForm action={adminCategoryAction} className="panel-body stack"><input name="categoryId" type="hidden" value={c.id}/><div className="form-grid"><Field label="Category name"><input name="name" defaultValue={c.name} required/></Field><Field label="Category slug"><input name="slug" defaultValue={c.slug} required pattern="[a-z0-9-]+"/></Field></div><Field label="Description"><input name="description" defaultValue={c.description}/></Field><div><SubmitButton>Save category</SubmitButton></div></ActionForm></details>)}</div>;
}

async function Listings() {
  const listings = await db.referralListing.findMany({include:{program:true,referrer:{include:{profile:true}},_count:{select:{transactions:true}}},orderBy:{createdAt:"desc"},take:100});
  return <div className="stack"><div className="notice">Approve only valid offers on programs whose terms permit bounty sharing. Disabling a listing prevents new referrals and preserves existing transaction records.</div>{listings.length ? listings.map(l=><details className="panel disclosure" key={l.id}><summary><span>{l.program.name} · @{l.referrer.profile?.username}<span className="tiny muted">{l.isDemo ? "Demo listing · " : ""}<Money cents={l.bountyCents}/> bounty</span></span><StatusBadge status={l.status}/></summary><div className="panel-body stack"><dl className="detail-list"><div><dt>Referral URL</dt><dd className="break-word">{l.referralUrl}</dd></div><div><dt>Program restrictions</dt><dd><StatusBadge status={l.program.restrictionStatus}/></dd></div><div><dt>Requirements</dt><dd>{l.requirements}</dd></div><div><dt>Countries</dt><dd>{l.countries.join(", ")}</dd></div><div><dt>Referrer reward{l.rewardType !== "CASH" ? " (estimated value)" : ""}</dt><dd><Money cents={l.referrerRewardCents}/> · {l.rewardType}</dd></div><div><dt>Available slots</dt><dd>{l.availableSlots} / {l.totalSlots}</dd></div><div><dt>Started referrals</dt><dd>{l._count.transactions}</dd></div><div><dt>Expiration</dt><dd>{l.expiresAt?.toLocaleDateString("en-US") || "None"}</dd></div></dl>{l.notes && <p className="muted">{l.notes}</p>}<ActionForm action={adminListingAction} className="inline-form"><input type="hidden" name="listingId" value={l.id}/><Field label="Listing status"><select name="status" defaultValue={l.status === "PENDING_APPROVAL" ? "ACTIVE" : l.status}><option value="ACTIVE">Approve / active</option><option value="REJECTED">Reject</option><option value="DISABLED">Disable</option></select></Field><SubmitButton>Save status</SubmitButton></ActionForm></div></details>) : <EmptyState title="No listings to review"/>}</div>;
}

async function Transactions({ mode }: { mode: string }) {
  const where = mode === "verification" ? { status: { in: ["SIGNUP_REPORTED","AWAITING_VERIFICATION"] as ("SIGNUP_REPORTED" | "AWAITING_VERIFICATION")[] } } : mode === "payments" ? { status: "PAYOUT_PENDING" as const } : {};
  const transactions = await db.referralTransaction.findMany({where,include:{program:true,referrer:{include:{profile:true}},referredUser:{include:{profile:true}},_count:{select:{evidence:true,messages:true}}},orderBy:{updatedAt:"desc"},take:100});
  const [payouts,deposits] = mode === "payments" ? await Promise.all([db.payout.findMany({include:{user:{include:{profile:true}}},orderBy:{createdAt:"desc"},take:50}),db.deposit.findMany({include:{user:{include:{profile:true}}},orderBy:{createdAt:"desc"},take:50})]) : [[],[]];
  return <div className="stack">{mode === "payments" && <div className="notice notice-warning">{isDemoMode() ? "Demo payments create ledger entries and update balances without moving real funds." : "Payment execution requires configured Stripe accounts. Never mark an unpaid real transfer as completed."}</div>}
    {transactions.length ? transactions.map(t=><section className="panel" key={t.id}><div className="panel-header"><h2>{t.program.name} <span className="tiny muted">{t.id.slice(-8).toUpperCase()}{t.isDemo ? " · Demo" : ""}</span></h2><StatusBadge status={t.status}/></div><div className="panel-body stack"><div className="admin-tx-summary"><div><span className="tiny muted">Referrer → customer</span><strong>@{t.referrer.profile?.username} → @{t.referredUser.profile?.username}</strong></div><div><span className="tiny muted">Cash bounty / fee / net payout</span><strong><Money cents={t.bountyCents}/> / <Money cents={t.feeCents}/> / <Money cents={t.netPayoutCents}/></strong></div><div><span className="tiny muted">Evidence / messages</span><strong>{t._count.evidence} / {t._count.messages}</strong></div></div>{t.completionNote && <p className="muted">{t.completionNote}</p>}<div className="form-actions"><Link href={`/dashboard/transactions/${t.id}`} className="button button-secondary">Inspect transaction</Link>{t.referrerConfirmedAt && <span className="badge badge-success"><CheckCircle2 size={13}/>Referrer confirmed</span>}</div>{mode === "verification" && <ActionForm action={adminVerifyAction} className="stack"><input type="hidden" name="transactionId" value={t.id}/><div className="form-grid"><Field label="Verification decision"><select name="decision" defaultValue="approve"><option value="approve">Approve completion</option><option value="reject">Reject completion</option></select></Field><Field label="Verification note"><input name="note" placeholder="Reason and evidence reviewed" required minLength={5} maxLength={2000}/></Field></div><div><SubmitButton>Verify referral</SubmitButton></div></ActionForm>}{mode === "payments" && isDemoMode() && <ActionForm action={adminPayAction}><input type="hidden" name="transactionId" value={t.id}/><SubmitButton>Pay demo bounty</SubmitButton></ActionForm>}</div></section>) : <EmptyState title={mode === "verification" ? "Verification queue is clear" : mode === "payments" ? "No bounties awaiting payment" : "No transactions yet"} description={mode === "verification" ? "Completion reports will appear here for final review." : undefined}/>}
    {mode === "payments" && <><section className="panel"><div className="panel-header"><h2>Payout & withdrawal history</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Recipient</th><th>Amount</th><th>Provider</th><th>Status</th><th>Date</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id}><td>@{p.user.profile?.username}</td><td><Money cents={p.amountCents}/></td><td>{p.provider}{p.isDemo ? " · Demo" : ""}</td><td><StatusBadge status={p.status}/></td><td>{p.createdAt.toLocaleDateString("en-US")}</td></tr>)}</tbody></table></div>{!payouts.length && <div className="panel-body muted">No payouts recorded.</div>}</section><section className="panel"><div className="panel-header"><h2>Deposit history</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Amount</th><th>Provider</th><th>Status</th><th>Date</th></tr></thead><tbody>{deposits.map(d=><tr key={d.id}><td>@{d.user.profile?.username}</td><td><Money cents={d.amountCents}/></td><td>{d.provider}{d.isDemo ? " · Demo" : ""}</td><td><StatusBadge status={d.status}/></td><td>{d.createdAt.toLocaleDateString("en-US")}</td></tr>)}</tbody></table></div>{!deposits.length && <div className="panel-body muted">No deposits recorded.</div>}</section></>}
  </div>;
}

async function Disputes() {
  const disputes = await db.dispute.findMany({include:{openedBy:{include:{profile:true}},transaction:{include:{program:true,referrer:{include:{profile:true}},referredUser:{include:{profile:true}},_count:{select:{evidence:true,messages:true}}}}},orderBy:{createdAt:"desc"},take:100});
  return <div className="stack">{disputes.length ? disputes.map(d=><section className="panel" key={d.id}><div className="panel-header"><h2>{d.transaction.program.name} · {d.reason.replaceAll("_"," ").toLowerCase()}</h2><StatusBadge status={d.status}/></div><div className="panel-body stack"><p className="tiny muted">Opened by @{d.openedBy.profile?.username} on {d.createdAt.toLocaleDateString("en-US")}{d.isDemo ? " · Demo dispute" : ""}</p><p>{d.details}</p><p className="tiny muted">{d.transaction._count.evidence} evidence files · {d.transaction._count.messages} messages · Referrer @{d.transaction.referrer.profile?.username} · Customer @{d.transaction.referredUser.profile?.username}</p><div><Link href={`/dashboard/transactions/${d.transactionId}`} className="button button-secondary">Inspect history, evidence & messages</Link></div>{d.status === "RESOLVED" ? <div className="notice notice-success">{d.resolution}</div> : <ActionForm action={adminResolveDisputeAction} className="stack"><input name="disputeId" type="hidden" value={d.id}/><Field label="Dispute resolution"><select name="resolution" defaultValue="pay"><option value="pay">Approve customer bounty</option><option value="reject">Reject referral & release bounty</option><option value="cancel">Cancel & release bounty</option></select></Field><Field label="Resolution note"><textarea name="note" required minLength={10} rows={3} maxLength={2000}/></Field><div><SubmitButton>Resolve dispute</SubmitButton></div></ActionForm>}</div></section>) : <EmptyState title="No disputes to review"/>}</div>;
}

async function Fees() {
  const fee = await db.feeSetting.findUnique({where:{id:"global"}});
  return <section className="panel form-page"><div className="panel-header"><h2>Marketplace success fee</h2></div><ActionForm action={adminFeeAction} className="panel-body stack"><p className="muted">Fees apply to the customer’s cash bounty. Existing transactions keep their saved fee. Fees are capped at the bounty and are charged only on successful payouts.</p><div className="form-grid"><Field label="Percentage fee (%)"><input name="percentage" type="number" min="0" max="100" step="0.01" defaultValue={(fee?.percentageBps || 0)/100} required/></Field><Field label="Fixed fee (USD)"><input name="fixed" type="number" min="0" step="0.01" defaultValue={(fee?.fixedCents || 0)/100} required/></Field><Field label="Minimum fee (USD)"><input name="minimum" type="number" min="0" step="0.01" defaultValue={(fee?.minCents || 0)/100} required/></Field><Field label="Maximum fee (USD)" hint="Leave empty for no additional cap."><input name="maximum" type="number" min="0" step="0.01" defaultValue={fee?.maxCents == null ? "" : fee.maxCents/100}/></Field></div><div><SubmitButton>Save marketplace fees</SubmitButton></div><span className="tiny muted">Last updated {fee?.updatedAt.toLocaleString("en-US") || "Never"}</span></ActionForm></section>;
}

async function Fraud() {
  const flags = await db.fraudFlag.findMany({include:{user:{include:{profile:true}},transaction:{include:{program:true}}},orderBy:{createdAt:"desc"},take:100});
  return <div className="stack"><section className="panel"><div className="panel-header"><h2>Create a fraud flag</h2></div><ActionForm action={adminFraudAction} className="panel-body stack"><div className="form-grid"><Field label="User ID (optional)"><input name="userId"/></Field><Field label="Transaction ID (optional)"><input name="transactionId"/></Field></div><Field label="Reason"><textarea name="reason" required minLength={10} rows={3} maxLength={2000}/></Field><div><SubmitButton className="button button-secondary">Flag for investigation</SubmitButton></div></ActionForm></section>{flags.length ? flags.map(f=><section className="panel" key={f.id}><div className="panel-header"><h2>{f.user?.profile?.username ? `@${f.user.profile.username}` : f.transaction?.program.name || "Activity flag"}</h2><span className={`badge ${f.resolvedAt ? "badge-success" : "badge-warning"}`}>{f.resolvedAt ? "Resolved" : f.severity}</span></div><div className="panel-body stack"><p>{f.reason}</p><span className="tiny muted">{f.createdAt.toLocaleString("en-US")}{f.isDemo ? " · Demo fraud flag" : ""}</span>{f.transactionId && <Link className="text-link" href={`/dashboard/transactions/${f.transactionId}`}>Inspect transaction →</Link>}{!f.resolvedAt && <ActionForm action={adminFraudAction}><input name="flagId" type="hidden" value={f.id}/><input name="reason" type="hidden" value="Reviewed and resolved by administrator"/><SubmitButton className="button button-secondary">Mark flag resolved</SubmitButton></ActionForm>}</div></section>) : <EmptyState title="No fraud flags" description="Suspicious activity flags and manual investigations appear here."/>}</div>;
}

async function Audit() {
  const actions = await db.adminAction.findMany({include:{admin:{include:{profile:true}}},orderBy:{createdAt:"desc"},take:100});
  return <section className="panel table-wrap"><table className="data-table"><thead><tr><th>Action</th><th>Administrator</th><th>Entity</th><th>Details</th><th>Time</th></tr></thead><tbody>{actions.map(a=><tr key={a.id}><td><strong>{a.action}</strong>{a.isDemo && <span className="tiny muted">Demo audit record</span>}</td><td>@{a.admin.profile?.username}</td><td className="tiny">{a.entityType}<br/>{a.entityId}</td><td className="tiny break-word">{a.details ? JSON.stringify(a.details) : "—"}</td><td className="tiny muted">{a.createdAt.toLocaleString("en-US")}</td></tr>)}</tbody></table>{!actions.length && <div className="panel-body muted">No administrative actions recorded.</div>}</section>;
}

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ tab?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const tab = tabs.includes(query.tab || "") ? query.tab! : "analytics";
  const content = tab === "analytics" ? <Analytics/> : tab === "users" ? <Users/> : ["programs","restrictions","terms"].includes(tab) ? <Programs mode={tab}/> : tab === "categories" ? <Categories/> : tab === "listings" ? <Listings/> : ["transactions","verification","payments"].includes(tab) ? <Transactions mode={tab}/> : tab === "disputes" ? <Disputes/> : tab === "fees" ? <Fees/> : tab === "fraud" ? <Fraud/> : <Audit/>;
  return <div className="stack"><PageHeading eyebrow="PROTECTED ADMIN CONSOLE" title={label(tab)} description="Review offers, protect participants, and keep every decision auditable." actions={<span className="badge badge-success"><ShieldCheck size={14}/>Admin access</span>}/>{isDemoMode() && <div className="notice notice-warning"><span className="badge badge-demo">Demo environment</span><span>Analytics include labeled sample records. All wallet movements are simulated.</span></div>}<nav className="tabs admin-tabs" aria-label="Administration sections">{tabs.map(t=><Link className={`tab ${tab === t ? "active" : ""}`} href={`/admin?tab=${t}`} key={t}>{label(t)}</Link>)}</nav>{content}</div>;
}
