import { settlementLabel } from '@/lib/manual-settlement';
import Link from 'next/link';
import { db } from '@/lib/db';
import { adminPaymentAction } from '@/lib/actions';
import { ActionForm,SubmitButton } from './action-form';
import { Field,Money,EmptyState } from './ui';
export async function AdminPayments(){
 const obligations=await db.paymentObligation.findMany({include:{payer:{include:{profile:true}},payee:{include:{profile:true}},transaction:{include:{program:true}},attempts:{orderBy:{createdAt:'desc'}},ledger:{orderBy:{createdAt:'desc'}}},orderBy:{updatedAt:'desc'},take:100});
 const fees=await db.ledgerEntry.aggregate({where:{account:'PLATFORM_REVENUE'},_sum:{amountCents:true}});
 return <div className="stack"><div className="notice">Post-verification payments. Debits include bounty plus fee. Payouts require settled funds. Demo controls simulate events; manual controls only record external payments.</div><div className="metric-card"><span className="metric-label">Recorded marketplace fee revenue</span><strong className="metric-value"><Money cents={fees._sum.amountCents||0}/></strong><span className="tiny muted">Includes demo/manual records and compensating reversals.</span></div>{obligations.map(o=>{
 const manual=o.provider==='manual';const options:[string,string][]=[];
 if(['CREATED','AUTHORIZED'].includes(o.status)) options.push(['start_debit',manual?'Record debit started':'Start demo debit'],['debit_success',manual?'Record debit received':'Simulate successful debit'],['debit_failure',manual?'Record debit failure':'Simulate debit failure'],['cancel','Cancel uncollected obligation']);
 if(['DEBIT_PENDING','DEBIT_PROCESSING'].includes(o.status)) options.push(['debit_success',manual?'Record debit received':'Simulate successful debit'],['debit_failure',manual?'Record debit failure':'Simulate debit failure']);
 if(o.status==='DEBIT_FAILED') options.push(['retry','Retry payment'],['cancel','Cancel uncollected obligation']);
 if(o.status==='FUNDS_PENDING') options.push(['funds_available','Mark funds available'],['refund',manual?'Record refund':'Simulate refund']);
 if(o.status==='FUNDS_AVAILABLE') options.push(['start_payout',manual?'Record payout started':'Simulate payout'],['payout_paid',manual?'Mark payout paid':'Simulate payout paid'],['refund',manual?'Record refund':'Simulate refund']);
 if(o.status==='PAYOUT_PROCESSING') options.push(['payout_paid',manual?'Mark payout paid':'Simulate payout paid']);
 if(o.status==='PAID') options.push(['refund',manual?'Record refund after recovery':'Simulate full refund']);
 if(manual)options.push(['adjustment','Record manual adjustment']);
 return <section className="panel" key={o.id}><div className="panel-header"><h2>{o.transaction.program.name} · {o.id.slice(-8)}</h2><span className="badge badge-muted">{settlementLabel(o.status,o.provider)}</span></div><div className="panel-body stack"><div className="inline-badges"><span className="badge badge-demo">{manual?'Manual record only':'Demo payment'}</span><span>@{o.payer.profile?.username} → @{o.payee.profile?.username}</span></div><dl className="detail-list"><div><dt>Customer bounty</dt><dd><Money cents={o.bountyCents}/></dd></div><div><dt>Marketplace fee charged to referrer</dt><dd><Money cents={o.feeCents}/></dd></div><div><dt>Total referrer payment</dt><dd><Money cents={o.totalDebitCents}/></dd></div><div><dt>Customer payout</dt><dd><Money cents={o.bountyCents}/></dd></div><div><dt>Failed attempts</dt><dd>{o.failedAttempts}</dd></div></dl><Link className="text-link" href={`/dashboard/transactions/${o.referralTransactionId}`}>Inspect referral and evidence</Link>{options.length>0&&<ActionForm action={adminPaymentAction} className="stack"><input type="hidden" name="obligationId" value={o.id}/><Field label="Payment action"><select name="operation">{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field>{manual&&<><Field label="External receipt/reference (no bank account numbers)"><input name="reference" required maxLength={150}/></Field><Field label="Record note"><textarea name="note" required minLength={10} maxLength={2000}/></Field><label className="checkbox-field"><input type="checkbox" name="recoveryConfirmed"/>External customer funds were recovered before recording a paid-referral refund.</label><details><summary>Manual adjustment fields</summary><Field label="Adjustment amount (USD)"><input type="number" name="amount" min="0.01" step="0.01"/></Field><Field label="Participant"><select name="userId"><option value={o.payerUserId}>Referrer</option><option value={o.payeeUserId}>Customer</option></select></Field><Field label="Unique adjustment key"><input name="adjustmentKey" minLength={8} maxLength={100}/></Field></details></>}<div><SubmitButton>Record payment action</SubmitButton></div></ActionForm>}<details><summary>Provider attempts and immutable ledger</summary>{o.attempts.map(a=><p key={a.id}>{a.operation} #{a.attemptNumber}: {a.status.toLowerCase()}</p>)}{o.ledger.map(e=><p className="tiny muted" key={e.id}>{e.type} · {e.account} · <Money cents={e.amountCents}/> · {e.description}</p>)}</details></div></section>})}{!obligations.length&&<EmptyState title="No post-verification obligations" description="Verify a new referral to create one. Historical wallet settlements remain separate below."/>}</div>;
}
