import Link from 'next/link';
import { db } from '@/lib/db';
import { adminUserAction } from '@/lib/actions';
import { ActionForm,SubmitButton } from './action-form';
import { EmptyState,StatusBadge } from './ui';
export async function AdminAccounts({query='',id}:{query?:string;id?:string}){
 const users=await db.user.findMany({where:{...(id?{id}:{}),...(query?{OR:[{email:{contains:query,mode:'insensitive'}},{profile:{username:{contains:query,mode:'insensitive'}}},{profile:{displayName:{contains:query,mode:'insensitive'}}}]}:{})},select:{id:true,email:true,role:true,isDemo:true,accountStatus:true,emailVerified:true,emailVerifiedAt:true,createdAt:true,closureRequestedAt:true,profile:{select:{username:true,displayName:true}},_count:{select:{listings:true,referralsOffered:true,referralsUsed:true,openedDisputes:true,fraudFlags:true}},listings:{select:{id:true,status:true,program:{select:{name:true}}},take:10,orderBy:{createdAt:'desc'}},referralsOffered:{select:{id:true,status:true,program:{select:{name:true}}},take:10,orderBy:{createdAt:'desc'}},referralsUsed:{select:{id:true,status:true,program:{select:{name:true}}},take:10,orderBy:{createdAt:'desc'}},openedDisputes:{select:{id:true,status:true,reason:true},take:10},fraudFlags:{select:{id:true,severity:true,reason:true,resolvedAt:true},take:10},securityEvents:{select:{id:true,action:true,createdAt:true},orderBy:{createdAt:'desc'},take:20}},orderBy:{createdAt:'desc'},take:100});
 const audits=id?await db.adminAction.findMany({where:{entityType:'User',entityId:id},select:{id:true,action:true,createdAt:true},orderBy:{createdAt:'desc'},take:30}):[];
 return <div className="stack"><form method="get" className="panel panel-body form-actions"><input type="hidden" name="tab" value="users"/><label>Search email or public profile<input name="q" defaultValue={query} maxLength={100}/></label><button className="button button-secondary">Search users</button></form>{users.map(u=><details key={u.id} className="panel disclosure" open={!!id}><summary><span>{u.profile?.displayName||'Member'} · @{u.profile?.username} {u.isDemo?'· Hidden demo account':''}</span><StatusBadge status={u.accountStatus}/></summary><div className="panel-body stack"><p>{u.email} · {u.role} · Email {u.emailVerified?'verified':'not verified'}</p><p className="tiny">Joined {u.createdAt.toLocaleDateString('en-US')} · {u._count.listings} listings · {u._count.referralsOffered+u._count.referralsUsed} transactions · {u._count.openedDisputes} disputes · {u._count.fraudFlags} fraud flags</p><Link href={`/admin?tab=users&user=${u.id}`} className="text-link">Inspect account and moderation audit →</Link>{u.role!=='ADMIN'&&u.accountStatus!=='CLOSED'&&<ActionForm action={adminUserAction} className="form-actions"><input type="hidden" name="userId" value={u.id}/><select name="status" defaultValue={u.accountStatus}><option>ACTIVE</option><option>RESTRICTED</option><option>SUSPENDED</option></select><SubmitButton>Update account access</SubmitButton></ActionForm>}{u.closureRequestedAt&&<p>Closure requested {u.closureRequestedAt.toLocaleDateString('en-US')}. Historical records retained.</p>}<h3>Listings</h3>{u.listings.map(l=><p key={l.id}>{l.program.name} · {l.status} · {l.id}</p>)}<h3>Transactions</h3>{[...u.referralsOffered,...u.referralsUsed].map(t=><Link key={t.id} href={`/dashboard/transactions/${t.id}`}>{t.program.name} · {t.status} →</Link>)}<h3>Disputes and fraud flags</h3>{u.openedDisputes.map(d=><p key={d.id}>{d.status}: {d.reason}</p>)}{u.fraudFlags.map(f=><p key={f.id}>{f.resolvedAt?'Resolved':f.severity}: {f.reason}</p>)}<h3>Security activity</h3>{u.securityEvents.map(e=><p className="tiny" key={e.id}>{e.createdAt.toLocaleString('en-US')} · {e.action}</p>)}</div></details>)}{audits.length>0&&<section className="panel panel-body"><h3>Account moderation history</h3>{audits.map(a=><p key={a.id}>{a.createdAt.toLocaleString('en-US')} · {a.action}</p>)}</section>}{!users.length&&<EmptyState title="No matching accounts"/>}</div>;
}
