import Link from 'next/link';
import { type ProgramOfferChange, type ProgramOffer } from '@prisma/client';
import { db } from '@/lib/db';
import { monitoringProviderStatus } from '@/lib/monitoring/providers';
import { Money, StatusBadge } from './ui';
const when=(date:Date)=>date.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'UTC',timeZoneName:'short'});
export function MonitoringChangeFacts({change}:{change:ProgramOfferChange}) {
 const detail=change.details&&typeof change.details==='object'&&!Array.isArray(change.details)?change.details as Record<string,unknown>:{};
 const value=(v:unknown)=>v===undefined||v===null?'Not previously established':typeof v==='string'?v:JSON.stringify(v);
 const score=typeof detail.confidenceScore==='number'?`${Math.round(detail.confidenceScore*100)}%`:`${change.confidence.toLowerCase()} confidence`;
 return <div className="stack"><div className="monitor-change-meta"><span>{when(change.detectedAt)}</span><span>{score}</span><StatusBadge status={change.reviewStatus}/></div>{typeof detail.field==='string'&&<><span className="label">Changed field: {detail.field.replaceAll('_',' ')}</span><div className="monitor-change-facts"><div><span className="label">Previous</span><strong>{value(detail.previous)}</strong></div><div><span className="label">Detected</span><strong>{value(detail.next)}</strong></div></div></>}{change.sourceUrl&&<p className="tiny break-word">Source: {change.sourceUrl.startsWith('https://')?<a href={change.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-link">{change.sourceUrl}</a>:change.sourceUrl}</p>}{change.reviewStatus==='VERIFIED'&&<p className="tiny">{detail.extractionMethod&&typeof detail.extractionMethod==='string'?`Extraction: ${detail.extractionMethod}`:'Reviewed historical change'}</p>}</div>;
}
export function ProgramMonitoringVersions({offers}:{offers:(ProgramOffer&{snapshot?:{confidenceScore:number|null;rawSnapshotHash:string|null;extractionMethod:string|null}|null})[]}) {
 return <details className="disclosure monitor-history"><summary>Current facts & previous versions ({offers.length})</summary><div className="stack">{offers.map(o=><div className="source-summary" key={o.id}><div className="inline-badges"><StatusBadge status={o.reviewStatus}/><span className="tiny">{o.isCurrent?'Current':'Historical / candidate'} · {o.scopeKey} · {when(o.detectedAt)}{o.isDemo?' · Demo data':''}</span></div><p><strong>Company signup offer:</strong> {o.standardSignupBonus||(o.referredRewardAmount!==null?`${o.referredRewardAmount.toLocaleString()} ${o.referredRewardCurrency}`:'Not established')}</p><p><strong>Referrer reward:</strong> {o.referrerRewardSummary||(o.referrerRewardAmount!==null?(o.referrerRewardCurrency==='USD'?<Money cents={o.referrerRewardAmount}/>:`${o.referrerRewardAmount.toLocaleString()} ${o.referrerRewardCurrency}`):'Not established')}</p><p>{o.qualificationRequirement||'No verified requirements recorded'}</p><p className="tiny">Expiration: {o.expiresAt?when(o.expiresAt):'Not established'} · Public posting: {o.publicPostingAllowed||'unclear'} · Incentive sharing: {o.incentiveSharingAllowed||'unclear'}</p>{o.snapshot&&<p className="tiny break-word">Confidence: {o.snapshot.confidenceScore===null?'Not scored':`${Math.round(o.snapshot.confidenceScore*100)}%`} · Method: {o.snapshot.extractionMethod||'Not recorded'} · Raw snapshot: {o.snapshot.rawSnapshotHash||'Not recorded'}</p>}{o.sourceUrl&&<p className="tiny break-word">Source: {o.sourceUrl}</p>}</div>)}{!offers.length&&<p>No historical versions captured yet.</p>}</div></details>;
}
export async function MonitoringOverview() {
 const now=new Date();const today=new Date(now);today.setUTCHours(0,0,0,0);const next=new Date(now);next.setUTCHours(6,0,0,0);if(next<=now)next.setUTCDate(next.getUTCDate()+1);
 const [checked,changed,errors,reviews,broken,low,last,changes]=await Promise.all([
  db.program.count({where:{lastCheckedAt:{gte:today}}}),db.program.count({where:{lastChangedAt:{gte:today}}}),db.program.count({where:{OR:[{consecutiveFailures:{gt:0}},{sources:{some:{snapshots:{some:{retrievedAt:{gte:today},extractionStatus:'AI_FAILED'}}}}}]}}),db.monitoringReview.count({where:{status:'PENDING'}}),db.programSource.count({where:{active:true,lastStatus:'UNAVAILABLE'}}),db.programSourceSnapshot.count({where:{retrievedAt:{gte:today},extractionConfidence:'LOW',isDemo:false,error:null}}),db.monitoringRun.findFirst({where:{status:'COMPLETED',programsChecked:{gt:0}},orderBy:{completedAt:'desc'}}),db.programOfferChange.findMany({include:{program:{select:{name:true}},newOffer:{select:{verificationMethod:true,isDemo:true}}},orderBy:{detectedAt:'desc'},take:20}),
 ]);
 const provider=monitoringProviderStatus();
 return <><div className="monitor-summary">{[['Programs checked today',checked],['Programs changed today',changed],['Programs with errors',errors],['Pending reviews',reviews],['Broken / unavailable sources',broken],['Low-confidence checks today',low]].map(([label,value])=><article key={label}><span className="label">{label}</span><strong>{value}</strong></article>)}</div><div className="notice"><div className="monitor-config"><span>AI extraction: {provider.ai?'Credentials supplied':'Not configured — manual review'}</span><span>Official-domain search: {provider.search?'Credentials supplied':'Not configured — preserve broken URLs'}</span></div><p className="tiny" style={{marginTop:10}}>Last fully successful batch: {last?.completedAt?when(last.completedAt):'Not recorded'} · Next expected daily dispatcher: {when(next)} · Programs default to a 24-hour cadence. Counts include labeled demo fixtures; they do not prove external websites were retrieved.</p></div><details className="disclosure"><summary>Recent field changes ({changes.length})</summary><div className="stack">{changes.map(c=><article className="source-summary" key={c.id}><h3>{c.program.name}{c.newOffer?.isDemo?' · Demo observation':''}</h3><MonitoringChangeFacts change={c}/>{c.newOffer?.verificationMethod&&<p className="tiny">Approval method: {c.newOffer.verificationMethod}</p>}<Link href={`/admin?tab=monitoring#program-${c.programId}`} className="text-link">View program history →</Link></article>)}{!changes.length&&<p>No detected changes yet.</p>}</div></details></>;
}
