import { db } from '@/lib/db';
import { configuredProvider } from '@/lib/payment-providers';
import { trustStatus } from '@/lib/payment-policy';
import { paymentMethodAction,paymentAuthorizationAction } from '@/lib/actions';
import { ActionForm,SubmitButton } from './action-form';
import { StatusBadge } from './ui';
export async function PaymentSettings({userId}:{userId:string}) {
 const provider=configuredProvider();
 const [user,methods]=await Promise.all([db.user.findUniqueOrThrow({where:{id:userId},include:{profile:true}}),db.paymentMethod.findMany({where:{userId,provider,status:{not:'DISCONNECTED'}},include:{authorizations:{where:{status:'ACTIVE'},orderBy:{acceptedAt:'desc'},take:5}},orderBy:{updatedAt:'desc'}})]);
 const trust=trustStatus(user,user.profile?.identityVerified);
 return <section className="panel"><div className="panel-header"><h2>Payment Settings</h2><StatusBadge status={trust.tier}/></div><div className="panel-body stack"><div className="notice notice-warning">{provider==='demo'?'Demo payment mode — no real money is being moved. Demo bank details and consent are simulated.':'Manual record mode. ReferMarket does not connect to a bank, create an ACH mandate, or move funds. Administrators record external receipts.'}</div><p>List your referral for free. You are only charged if your referral successfully converts. The customer receives the full bounty; the success fee is added to your payment.</p><dl className="detail-list"><div><dt>Payment reliability</dt><dd>{trust.reliability===null?'No payment history':`${trust.reliability}%`}</dd></div><div><dt>Successful payments</dt><dd>{user.successfulPaymentCount}</dd></div><div><dt>Failed payments</dt><dd>{user.failedPaymentCount}</dd></div><div><dt>Late payments</dt><dd>{user.latePaymentCount}</dd></div></dl>{methods.map(method=><div className="panel panel-body stack" key={method.id}><strong>{method.bankName} · •••• {method.last4}</strong><div className="inline-badges"><StatusBadge status={method.status}/><span>Authorization: {method.authorizationStatus.toLowerCase()}</span></div><p className="tiny muted">{provider==='demo'?'This fictional bank also serves as your demo payout method.':'This is a record of an external payment arrangement, not a verified bank account.'}</p>{method.authorizationStatus!=='ACTIVE'&&<ActionForm action={paymentAuthorizationAction} className="stack"><input type="hidden" name="methodId" value={method.id}/><input type="hidden" name="scope" value="MARKETPLACE_BOUNTIES"/><label className="checkbox-field"><input type="checkbox" name="consent" required/>I agree to {provider==='demo'?'simulate':'record consent for'} collection of verified referral bounties plus the separately disclosed success fee. Terms: {provider==='demo'?'demo-bounties-v1':'manual-recording-v1'}. This is not a real ACH authorization.</label><div><SubmitButton>{provider==='demo'?'Authorize demo referral payments':'Record manual settlement consent'}</SubmitButton></div></ActionForm>}{method.authorizations.map(a=><p className="tiny muted" key={a.id}>Consent {a.scope.toLowerCase().replaceAll('_',' ')} · {a.termsVersion} · accepted {a.acceptedAt.toLocaleDateString('en-US')}</p>)}<ActionForm action={paymentMethodAction}><input type="hidden" name="methodId" value={method.id}/><input type="hidden" name="operation" value="disconnect"/><SubmitButton className="button button-secondary">Disconnect and revoke consent</SubmitButton></ActionForm></div>)}{!methods.length&&<ActionForm action={paymentMethodAction}><input type="hidden" name="operation" value="connect"/><SubmitButton>{provider==='demo'?'Connect demo bank account':'Record manual payment arrangement'}</SubmitButton></ActionForm>}</div></section>;
}
